### ISSUE TITLE
Service calls rcl_interfaces

### ISSUE THREAD

**Issue by martinfri** [v-kiniv/rws#4]
Hi @v-kiniv 
Cool library!
Im trying it out a bit, pub sub works great and some service calls.
But i get a silent crash when i try to call a service with the following interface
```
/foo/list_parameters
rcl_interfaces/srv/ListParameters
``` 
The same goes for other services of rcl_interface types.
The line that seems failing is:
```c++
rmw_deserialize(sm, req_ts_hdl_, buf.get());
``` 

Any ideas what might cause this issue?
Do all nodes that i spawn run rmw_fastrtps_dynamic_cpp?

- Library Version: ros2
- ROS Version: Humble
- Platform / OS: Ubuntu 22.04

**Comment by v-kiniv** [comment]
@martinfri Hi, please check #5 and let me know if it fixes the issue

**Comment by martinfri** [comment]
@v-kiniv Yes that solves the issue, thanks!

I have made some local improvments/changes as well is it ok to create pull requests to the repo?

**Comment by v-kiniv** [comment]
@martinfri Great, then I think we can merge #5 and close this issue.
Sure, PR's are welcome.
